### ISSUE TITLE
Response headers missing from logs when making use of default serializers

### ISSUE THREAD

**Issue by arthurw1** [seek-oss/logger#9]
## Description

When making use of default serializers as below, the response headers in log simply appears as `"headers": "[Function]"` rather than the expected list of headers.

Express example with logging middleware implementation:
```
app.use(function (req, res, next) {
  logger.info({ req, res });
  next();
})
```

It looks like the default `seek-oss/logger` serializer tries to extract `res.headers` which is a function in the `res` object.

## Steps to reproduce (for bugs)

See description.

## Possible Implementation

We could extract the headers with `res.getHeaders()`. See here: https://nodejs.org/api/http.html#http_response_getheaders

## Context
Use case: we are trying to log all incoming HTTP requests.

**Comment by 72636c** [comment]
Hey @arthurw1! A couple of generalities here:

1. We don't recommend logging every HTTP request in application code due to cost implications. If you're deploying to a SEEK-standard runtime environment then you likely have a sidecar that already handles generic request logging.

1. We don't recommend blasé logging as described in the example. Those objects are internal to Express and could conceivably contain sensitive (PII or security-related) information. These can be contained in request or response bodies, or propagated between middlewares via e.g. `locals`.

Happy to discuss this further internally if you'd prefer. You can reach out in our shared channels like `#apna-jag`.

**Comment by arthurw1** [comment]
@72636c Thanks for your input! I'll speak to my team about it.

But putting the use case aside, the code [here](https://github.com/seek-oss/logger/blob/8849e37c9396bd9f6011f394744daf2365f18748/src/serializers/index.ts#L19) doesn't seem to work as intended, i.e. the following are undefined (for a bare-bones nodejs http server):
   - `res._headers`
   - `res.header`
   - `res.headers`

However, `res._header` does provide you with header info as a string.

**Comment by 72636c** [comment]
👍 thanks for looking into this. Would you be open to submitting the fix?

**Comment by arthurw1** [comment]
Yup, I can do that!
